name: list-secrets
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  list:
    uses: logiskbrist/logisk-platform-workflows/.github/workflows/list-secrets.yaml@v3
    secrets: inherit
